### ISSUE TITLE
`getDeviceInterests` doesn't support pagination as per API docs

### ISSUE THREAD

**Issue by Harsh-br0** [pusher/push-notifications-web#115]
This is a follow-up of #80
As per this [issue-comment](https://github.com/pusher/push-notifications-web/issues/80#issuecomment-1291923078) 

> # Bug Report
> 
> The `getDeviceInterests` method does not implement the pagination protocol used by the handler
>##  Reproduction Steps
> 
> Call `getDeviceInterests` on a device that has > 100 subscriptions
>###  Expected Result
> 
> All device interests should be returned
>###  Actual Result
> 
> Only the first 100 interests (the first page) will be returned

**Comment by britneycodes** [comment]
Hey @Harsh-br0 , thanks for your submission! Could I have your email address so we can send you some swag?

**Comment by Harsh-br0** [comment]
> Could I have your email address so we can send you some swag?

Nvm , the email is in shambles now
