### ISSUE TITLE
iOS / macOS Safari Push API Support

### ISSUE THREAD

**Issue by dgoudie** [pusher/push-notifications-web#138]
Hi!

What is the status of support notification delivery using W3C standards-based Web Push for iOS and macOS Safari?

* macOS Ventura / Safari 16.1 and up have support.
* iOS 16.4 (currently beta) Safari added support recently.

Per the guidance from Apple [here](https://developer.apple.com/documentation/usernotifications/sending_web_push_notifications_in_safari_and_other_browsers#overview), it looks like the websites should move forward with adapting the W3C standard notification implementation (even though Safari on macOS supports both)

In my testing on iOS 16.4 beta, Apple did not add the old Safari-specific APIs (`window.safari.pushNotification` is not defined).

When playing around with the newest `@pusher/push-notifications-web` libraries, I ran into the following issues:

* `2.0.0-beta.2`: Works as intended on macOS Safari, but does not work on 16.4 beta iOS Safari (since it seems to use the old safari notifications APIs)
* `2.0.1`: Doesn't work on either iOS or macOS, since the library identifies via the user-agent that the browser is Safari, and leaves a console warning identifying lack of support.
    *  As an attempted workaround, I spoofed the user-agent to match a few different supported browsers, but receive an error `Push service endpoint not supported. The push subscription might be from an unsupported browser`. The API call to fetch the web-vapid-public-key seems to work just fine, but the subsequent call to `https://instance_id.pushnotifications.pusher.com/device_api/v1/instances/instance_id/devices/web` fails with a 400 BAD_REQUEST.

Obviously this stuff takes time to build, and these changes are pretty new on Apple's part, so this is all to be expected. I was just looking to open a discussion and share what I've found so far.

**Comment by iedev1** [comment]
I just want to pop in to ask the team if there's any update on this at all? This is a massive update for PWA on iOS and we'd love to know whether this will be supported by Pusher or not.

We still get `Could not add Device Interest. SDK not registered` errors when using this on MacOS and iOS.

**Comment by benw-pusher** [comment]
At this time we are not able to commit to support for Push API support on iOS / Safari.

**Comment by gbaggaley** [comment]
Why is this? Firebase FCM looks like it has support for this already which we will probably have to move to as an alternative.

I've also noticed macOS Safari notifications aren't working since upgrading to Ventura. Could this be due to macOS Safari now using the Push API instead of the old Safari notification API?
