### ISSUE TITLE
undefined is not an object (evaluating 'window.safari.pushNotification')

### ISSUE THREAD

**Issue by b6oh** [pusher/push-notifications-web#141]
Safari on iOS allows push notifications when the app is a home screen app since iOS 16.4. Currently i get the error `undefined is not an object (evaluating 'window.safari.pushNotification')` with `2.0.0-beta.2` when registering the device on a home screen app on iOS.  Is there something I can do?

**Comment by benw-pusher** [comment]
At this time Beams does not support Web Push notifications on Safari/iOS.
