### ISSUE TITLE
Safari Support

### ISSUE THREAD

**Issue by cl0ckwork** [pusher/push-notifications-web#142]
I've followed the walkthrough [here](https://pusher.com/docs/beams/getting-started/web/configure-safari/) to setup certificates, ive also installed the 2.0.1 sdk, and I see the following issue in safari on the local app. 

```
[Error] Unhandled Promise Rejection: SecurityError: Script http://localhost:3000/service-worker.js?pusherBeamsWebSDKVersion=2.0.1 load failed
```

this works fine on Chrome via localhost - I've looked around and can't seem to find anything obvious, is there something i am missing? also, is this correct? i thought safari would be supported, based on the docs (referenced above) https://github.com/pusher/push-notifications-web/blob/13c861e66c60a498cdaa9c170574f63f6a8a74de/src/push-notifications.js#L536

seeing this locally as well
<img width="843" alt="image" src="https://github.com/pusher/push-notifications-web/assets/29135200/a9ff5d22-5aae-46fe-8fe7-6e31124e9e31">

**Comment by b6oh** [comment]
You have to install 2.0.0-beta.2 for working push notifications in safari desktop. Mobile safari is not yet supported by beams.

**Comment by benw-pusher** [comment]
@b6oh is correct, at this time we don't support web push on Safari / iOS and you would need to use the beta version of the library for native Safari notifications.

**Comment by benw-pusher** [comment]
We will use https://github.com/pusher/push-notifications-web/issues/146 to keep track of this request
