### ISSUE TITLE
iOS Web Push on PWA

### ISSUE THREAD

**Issue by micio86dev** [pusher/push-notifications-web#143]
Hi, We are trying to enable push notifications on a PWA. On Android (Chrome) it works, but on iOS (PWA installed or Safari) we get nothing. We have the following error on iPhone: undefined object window.safari.pushnotification. While on safari Desktop version it works correctly.
We wanted to know if there is no support yet and if you plan to update the library soon to support it.

A thousand thanks

Best regards

**Comment by benw-pusher** [comment]
At this time we don't have support for web push on iOS Safari.

**Comment by benw-pusher** [comment]
We will use #146 to keep track of this request
