### ISSUE TITLE
Feature Request: Typescript Types

### ISSUE THREAD

**Issue by brett-east** [pusher/push-notifications-web#44]
Issue Type: **Feature**

Describe the issue:

I'm currently trying to use Pusher Beams and have to add '@pusher/push-notifications-web' to my declarations file, as there are no published types.

To get around this I'm having my linter try and infer types, but some are missing. It would just be really helpful if the typescript types were already available.

Thanks

**Comment by jonathanlloyd** [comment]
Hi! Thanks for the feedback :slightly_smiling_face: 
I've added this to our backlog & will provide an update here when this ships
