### ISSUE TITLE
Add support for querying Beams data inside the Service Worker

### ISSUE THREAD

**Issue by jonathanlloyd** [pusher/push-notifications-web#64]
There are times where it would be useful to be able to query Beams state inside the service worker.
For example:
 - You want to customize the notification based on the currently authenticated user
 - Notification customizations must be done in the `onNotificationReceived` handler in your service worker
 - Because you cannot currently access Beams state in the service worker, it is difficult to retrieve the currently authenticated user id

**Comment by daniel-shuy** [comment]
Implemented in #113
