### ISSUE TITLE
iOS Chrome not working

### ISSUE THREAD

**Issue by madroneropaulo** [pusher/push-notifications-web#73]
I get an error on Chrome for iOS

Erorr: Pusher Beams does not support this browser version.

Chrome 87.0.4280.77
iOS 14.2
iPhone Xr

**Comment by ben-pusher** [comment]
At this moment iOS browsers are not supported by Pusher Beams, as iOS browsers do not support the Push API. This is something that may be addressed in the future but is not on our current roadmap. 

You can use our [push-notification-swift ](https://github.com/pusher/push-notifications-swift)library for any native iOS apps that require push notifications.
