### ISSUE TITLE
deep_link: focus existing window

### ISSUE THREAD

**Issue by fromi** [pusher/push-notifications-web#94]
It is a common notification pattern to focus an existing window instead of opening a new window all the time when clicking on a notification: https://developers.google.com/web/fundamentals/push-notifications/common-notification-patterns#focus_an_existing_window

It would be nice to have such feature directly available. Right now, I have to forget about using deep_link to use some "data.link" property instead, and have a custom "notificationClick" listener to handle it.

**Comment by neelrocketbots** [comment]
Any news on this? This is an extremely important feature.

**Comment by daniel-shuy** [comment]
I have implemented this in #112
