### ISSUE TITLE
Notification isn't getting received. 

### ISSUE THREAD

**Issue by abhagsain** [pusher/push-notifications-web#96]
My server is sending notification to the client and I even tried to send a custom notification from the Debug Console but I'm not getting any notification on any of the devices. 
And please also clarify what's this **Device de-registered** event?

Thank you

![image](https://user-images.githubusercontent.com/36589645/119208074-37f09b80-babe-11eb-8556-17fe48fe01ae.png)

**Comment by abhagsain** [comment]
I just now received a notification but it's not what I sent from the debug console. 
It says **This site has been upgraded in the background** 

![image](https://user-images.githubusercontent.com/36589645/119208252-fdd3c980-babe-11eb-8483-24bf003ccf74.png)

**Comment by web-dev-ua** [comment]
I had the same problem. It turned out that I had 2 service workers connected. When I left only one, the problem disappeared.

**Comment by abhagsain** [comment]
> I had the same problem. It turned out that I had 2 service workers connected. When I left only one, the problem disappeared.

Yes, having multiple service-worker is the problem. I was using [next-pwa](https://github.com/shadowwalker/next-pwa) but it doesn't work well. 
Do you any references to make it work with an existing service-worker? How to pass push-notification control over to `Pusher Beams` and other stuff to `next-pwa`

[The Pusher setup docs](https://pusher.com/docs/beams/guides/existing-service-worker#initialize-the-sdk) shows that we just need to pass the initialized service-worker and Pusher will handle from thereon but no luck :(

**Comment by benw-pusher** [comment]
Were you sure to add the import line to the top of the existing service worker? `importScripts("https://js.pusher.com/beams/service-worker.js"); `

If you need further support it may be best to reach out to our support team at https://support.pusher.com/hc/en-us/requests/new

**Comment by abunour22** [comment]
same issue !

**Comment by benw-pusher** [comment]
Closing this as the original reporter has resolved the issue. @abunour22 and anyone who finds this in the future - please get in touch with us at https://support.pusher.com/hc/en-us/requests/new so we can assist you.
